### ISSUE TITLE
Files are not displayed when the page width is narrow (mobile especially)

### ISSUE THREAD

**Issue by keke1229488344** [sigoden/dufs#333] opened 2024-01-03 09:44 UTC
Hey! Thanks to this amazing project for helping me easily run webdav and display files by basic web.

But when I access the page on my mobile phone, I find that if the title of the folder is relatively long (but it is within the legal length), it will be displayed in a new line. Once this happens, none of the files in the folder will not be displayed on the page.

At first, I thought it was a mistake with my mobile browser, but now I can easily reproduce this issue in my computer chrome: **open the dufs website, enter a relatively long folder, and then narrow the browser window, you will find All the files in this folder disappear from the web interface!**

I'm currently using docker to deploy dufs, the image is: `sigoden/dufs@sha256:65b2af775272f7394c2c71ae6d0d5b5e0fe3382a071991a9b912f118a6215352`

dufs will be even better if this issue is solved, thanks in advance :-)

![image](https://github.com/sigoden/dufs/assets/17313185/3683146c-f5a7-40cb-b947-3606e1fd02da)
![image](https://github.com/sigoden/dufs/assets/17313185/33450009-1a43-476e-bbed-a6b3068be0b5)

**Comment by sigoden** [comment] 2024-01-03 12:04
Based on the information you provided, it is difficult for me to reproduce the question.

The most crucial information for me to locate the problem in the logs, don't skip it. @keke1229488344

**Comment by sigoden** [comment] 2024-01-05 00:41
Close this issue due to lack of information.

**Closed by sigoden** 2024-01-05 00:41 UTC

**Comment by ShouNichi** [comment] 2024-06-20 06:57
It is a frontend problem. When the title bar(folder name) gets too long, it will become multiple lines thus hiding the files.
