### ISSUE TITLE
During cls handshake connection from

### ISSUE THREAD

**Issue by Asmaelh** [sigoden/dufs#365] opened 2024-02-20 19:26 UTC
after some time (a couple of days), errors start going into the logs and the server stops accepting requests until you restart

2024-02-17T10:33:52+03:00 WARN - During cls handshake connection from 192.241.215.42:43624
2024-02-17T11:19:00+03:00 WARN - During cls handshake connection from 107.170.231.42:40164
2024-02-17T13:24:44+03:00 WARN - During cls handshake connection from 107.170.229.48:44398
2024-02-17T14:28:54+03:00 WARN - During cls handshake connection from 45.227.254.49:32175
2024-02-17T14:28:54+03:00 WARN - During cls handshake connection from 45.227.254.49:32427
2024-02-17T14:28:54+03:00 WARN - During cls handshake connection from 45.227.254.49:32974

Everything works well on version 0.37

**Environment:**
 - Dufs version: 0.40
 - OS info: Windows 10

**Comment by sigoden** [comment] 2024-02-20 23:49
Just a warning that there is something unusual about tls handshake. it's harmless, please ignore.
This problem may be solved in the near future, see hyperium/hyper#3427

**Comment by Asmaelh** [comment] 2024-02-21 03:21
> Just a warning that there is something unusual about tls handshake. it's harmless, please ignore. This problem may be solved in the near future, see [hyperium/hyper#3427](https://github.com/hyperium/hyper/issues/3427)

But then why does the program hang and does not respond to requests, I checked on several servers

**Comment by Asmaelh** [comment] 2024-02-21 03:22
On version 0.37 its OK

**Comment by sigoden** [comment] 2024-02-21 03:34
After #321 (from dufs v0.39.0),  dufs switched to hyper v1. This is probably where the problem is most likely to occur.

The warning log may not tell why the server stopped accepting requests.

What are the steps to reproduce the problem? The simpler and more direct the better. @Asmaelh

**Comment by Asmaelh** [comment] 2024-02-21 04:25
My config file:

serve-path: '../download'
bind:
  - 10.85.80.2
port: 9009
auth:
  - admin:$6$qCAVUG7yn7t/hH4d$BWm8r5MoDywNmDP/J3V2S2a6flmKHC1IpblfoqZfuK.LtLBZ0KFXP9QIfJP8RqL8MCw4isdheoAMTuwOz.pAO/@/:rw
allow-all: true
enable-cors: true
assets: ./assets/
log-format: '$remote_addr'
tls-cert: ./cert/cloud.crt
tls-key: ./cert/cloud.key

it's just that after a while the server becomes unavailable, even with a low load, and in the log here are the messages that were above

What else can I check?

**Comment by sigoden** [comment] 2024-02-21 07:34
According to your configuration, there should be some access logs as follows. Why don't they exist?
```
2024-02-21T07:30:08Z INFO - 192.168.8.8
```
Only by confirming the problem can I fix it.
I have tested 10,000 requests and still cannot reproduce the problem.
Can you restart again, wait for the problem to occur, and record all the logs generated? @Asmaelh

**Comment by sigoden** [comment] 2024-02-23 01:02
I have tested 100,000 requests and still cannot reproduce the problem.

I'll close this issue first. But new feedback is welcome.

**Closed by sigoden** 2024-02-23 01:02 UTC

**Comment by Asmaelh** [comment] 2024-02-23 03:57
it took 3 days and the server froze, this is the whole log, i.e. there were very few requests. There is no response in either the browser or the application

**Comment by sigoden** [comment] 2024-02-23 04:26
The logs show no obvious problem.
Can you check the memory and open handles of the dufs process and see if there are any leaks? @Asmaelh

**Comment by Asmaelh** [comment] 2024-02-23 04:54
there are no memory leaks, I do not know what else to look at. I'll stay on version 0.37 - it doesn't freeze.
