### ISSUE TITLE
corrupted files in zipped files

### ISSUE THREAD

**Issue by juliangaal** [sigoden/dufs#79] opened 2022-06-29 06:48 UTC
I'm experiencing issues when extracting files form an zip-archive. Downloading the individual .jpg files works fine, but they become corrupted during the zipping process and/or download.

Version: 0.22.0
OS: Ubuntu 18.04
Browser: FF 99.0

**Comment by sigoden** [comment] 2022-06-29 07:17
cloud you post the log?

**Comment by sigoden** [comment] 2022-06-30 07:20
Closing this issue due to lack of information. If anyone else encounters the same problem, welcome to reopen this issue。

**Comment by juliangaal** [comment] 2022-06-30 08:16
As far as I can tell from your logger.rs file you only log to stdout, so here you go:

```
Listening on:
  http://127.0.0.1:5000/
  http://172.17.0.1:5000/
  http://192.168.178.180:5000/
  http://[::1]:5000/
  http://[2003:cf:af3b:2500:1131:9987:7c10:32e9]:5000/
  http://[2003:cf:af3b:2500:1743:830c:e9fb:2204]:5000/

2022-06-30T10:15:13+02:00 INFO - 127.0.0.1 "GET /airbnbirgit/?zip" - 200
```

Are you writing to a logfile I can attach?

**Comment by sigoden** [comment] 2022-06-30 08:30
Is the zip format incompatible with mac? I have test linux and macos, No problem found。

**Comment by juliangaal** [comment] 2022-06-30 08:46
Well, I am on ubuntu 22.04 and tested with ff and chromium. Can't access MacOS to test.

**Comment by sigoden** [comment] 2022-06-30 08:49
Cloud you zip some unimportant files to reproduce the problem, then upload that zip file to this github issue?

**Comment by juliangaal** [comment] 2022-06-30 09:11
The original zip-file was filled with images, and my image viewer simply stated "Failed to open input stream for reading" when attempting to unzip it, which, to me, sounded like a zipping issue.

I tried to reproduce the issue with text files, but my text editor states that it's a permissions issue, because it doesn't have the permission to open the files!

I'm not sure where the permissions get mixed up however. I start the `dufs` binary without sudo, from my standard user account with `dufs -a` (just testing, everything on localhost), so dufs should be running as the standard user. Are any permissions changed during the upload process or zipping?

**Comment by sigoden** [comment] 2022-06-30 09:35
The user:group of files created by dufs is same to user:group that runs dufs. dufs won't mixup permissions.

The permissions of the unzipped files are controlled by the unzip tool and the user:group runs the tool.

Your may try online unzip tool like https://m.ezyzip.com/unzip-files-online.html

**Comment by juliangaal** [comment] 2022-06-30 09:40
The online tools works perfectly, no issue with extracting the files.

Using unzip from the terminal also results in the same issue. Very strange. No idea where to go from here, honestly.

**Comment by sigoden** [comment] 2022-06-30 09:48
Could you post the version information of your unzip tool?
> run `unzip -v` to print version info

**Comment by sigoden** [comment] 2022-06-30 09:55
I found the problem, the mode of the files in the zip file are all been set to `000`. So there will are permission problems in linux.

Your unzip tool is fine.

**Comment by sigoden** [comment] 2022-06-30 09:56
Thank you for helping me find the problem

**Closed** 2022-06-30 11:29 UTC

**Comment by juliangaal** [comment] 2022-06-30 12:08
works like a charm! Thanks for the quick response
